
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: savoria
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  
  rules:
  - host: savoria.local

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: savoria-service
            port:
              number: 80
      